# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  tag: '$(Build.BuildId)'

stages:
  - stage: Build
    displayName: Build Stage
    jobs:
    - job: Build
      displayName: Build Job
      pool: 
        name: 'AgentPC'
      steps:
      - task: Docker@2
        inputs: 
          containerRegistry: 'manual-aksdevopsacr-svc'
          repository: 'custom2aksnginxapp1'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
          tags: |
            $(tag)
            $(Build.SourceVersion)
      - task: KubernetesManifest@0
        displayName: Create imagePullSecret
        inputs:
          action: createSecret
          secretName: $(imagePullSecret)
          dockerRegistryEndpoint: $(dockerRegistryServiceConnection)

      - task: KubernetesManifest@0
        displayName: Deploy to Kubernetes cluster
        inputs:
          action: deploy
          manifests: |
            $(Pipeline.Workspace)/manifests/deployment.yml
            $(Pipeline.Workspace)/manifests/service.yml
          imagePullSecrets: |
            $(imagePullSecret)
          containers: |
            $(containerRegistry)/$(imageRepository):$(tag)